# Generated by Django 3.0.7 on 2023-02-13 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Watchlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviemodel',
            old_name='desription',
            new_name='description',
        ),
    ]
